### ISSUE TITLE
Weapon flipped when sharing a build

### ISSUE THREAD

**Issue by lyrgard** [lyrgard/ffbeEquip#102]
if you share a build for a unit without innate DW, and a Bowie Knife, Sasuke's Katana, or similar in the Left Hand slot with another weapon in the Right Hand, the sharing link will have the weapons flipped

**Comment by biovenger** [comment]
This one is tricky. The result comes from the need to place items in "ability" priority when creating a hash, as they are linearly equipped when a build is loaded. This is cleverly solved in getStateHash by adding them in priority order (allows-use-of, then dual wield, then the rest).

So, in short: build.js lines 1604 through 1630 all unit items are placed in priority order, and then in lines 1811 through 1821 they are equipped in a linear fashion.

A. Proposed "ok" solution
Build a list of all special effects (including allows-use-of) in the hashed build before equipping items in loadStateHashAndBuild. Add all these effects to a temporary list that fixItem can use as an optional parameter. fixItem will then not only check existing item restrictions but also check the list for any dual wields, allow-use-of, etc. Once the parsing is done, the temporary list can be discarded. All other uses of fixItem can stay as normal.

B. Best brute-force solution
Remove the priority order in lines 1604 through 1630 and just add items as-is in the exact same order as they are on the unit. Then when importing the build in loadStateHashAndBuild, do a quadruple-pass instead of lines starting with 1811, but allowing fixItem to fail silently (that is not spawn an alert). To clarify, go over the entire list, in an identical fashion, four consecutive times, while silencing all alerts. This will guarantee that allows-use-of and dual-wield items get added.

- First pass will add all initially equipable items, as well as any allows-use-of items
- Second pass will add any additional items through allows-use-of
- Third pass is a safeguard where the second pass might contain a dual-wield item (e.g. allows-use-of-katana allows marie to equip sasuke's katana, thus allowing her to equip two weapons in the third pass)
- Fourth pass adds all remaining items

It's not too inefficient because the list is always small (and fixed in size). But it does feel brute-forcy.

I can easily do the brute-force solution as a PR, if you think it's good enough, but the first solution is a bigger change I'm not too comfortable doing quickly or without a sensible discussion.
