### ISSUE TITLE
Share stats on FFBE Equip website usage

### ISSUE THREAD

**Issue by Indigo744** [lyrgard/ffbeEquip#153]
Hello!

Recently, while talking about FFBE Equip with some friends, I was asked how much this site was used by the community.

As I couldn't answered precisely, I remembered that you have Google Analytics on the website.

Would it be possible to share some usage stats?

Thanks!

**Comment by lyrgard** [comment]
So, some data I found on Googla Analytics : 

3.9k unique users daily, 65k per month
57% from desktop, 39% from mobile and 4% from tablets
36% from the USA, 8% from France, 6% from Canada, 5% from Brazil and 5% from Germany

To put the 65k per month into perspective, the last user vote banner received something like 3M votes. We got 14 tickets, so that's an equivalent of 215k users using all their voting tickets. More reasonable numbers is probably around 300-400k active users. It still means 20-15% of the players use my site.
