### ISSUE TITLE
Forcing mobile page to desktop site clears the build.

### ISSUE THREAD

**Issue by Darwe-Canine** [lyrgard/ffbeEquip#167]
Discovered by User Sic

Possible bug: when opening a link to a build on mobile, the page will open.  If the desktop site is requested, the page reloads and the build disappears. It also occurs when building a unit normally, and forcing the page from desktop to mobile or vice versa. Verified on Chrome for Android and when opening the links in the Discord app on Android.

**Comment by Indigo744** [comment]
This behavior is not surprising. When opening a build link, after loading all information, the current hash is reset.

Hence when requesting the desktop version, or when reloading the page, the browser will load the URL without the hash, hence without the build.

See `builder.js`, function `loadStateHashAndBuild()`:
```js
function loadStateHashAndBuild(data, importMode = false) {
    var dataVersion = data.version ? data.version : 0;

    /* ... blablabla... */
    
    selectUnitTab(0);
    dataLoadedFromHash = true;
    window.location.hash = ""; /* <-- this one is the culprit */
}
```

I am not sure right now why the hash is forcefully removed every time. Maybe @lyrgard can give some insight on this.

**Comment by Darwe-Canine** [comment]
And when you build a new build, it doesn't create a hash in the first place, so there is nothing to preserve the information when going into or out of desktop mode?

**Comment by Indigo744** [comment]
Since the whole page is reloaded, nothing is kept.

We could circumvent the issue by storing the current build inside localStorage (which is way faster than Google Drive, and doesn't need to be connected). Of course, saving should still save to the Google Drive.

**Comment by lyrgard** [comment]
The hash is removed to prevent users from thinking they can just copy the
url to get a link to the build. Also, keeping the hash would have no sense
as soon as the user change one thing in the build. So it was "safer" to
remove it.

**Comment by Indigo744** [comment]
Ok, I understand.

What about using localStorage to keep the current build state, even if the user change page / reload / request desktop site?

**Comment by lyrgard** [comment]
I don't know. I personally often refresh the page when I want to start a
new build from scratch, so keeping the old data would be a bother for me.
Also localStorage has no time limit, I don't know if reloading the previous
build the user made last week as much meaning.

Last point is, why use desktop mode? Is the mobile mode not enough? Would
it be possible to solve this problem by not needing to switch to desktop
mode?

Le 15 août 2018 20:42, "Guillaume" <notifications@github.com> a écrit :

Ok, I understand.

What about using localStorage to keep the current build state, even if the
user change page / reload / request desktop site?

—
You are receiving this because you were mentioned.

Reply to this email directly, view it on GitHub
<https://github.com/lyrgard/ffbeEquip/issues/167#issuecomment-413295073>,
or mute the thread

**Comment by Darwe-Canine** [comment]
I spoke with Sic, who noted the issue. He said that he uses the desktop view to see more things at once, to get a better overview. He also said that before this morning switching to the desktop site wouldn't blank the build.
