### ISSUE TITLE
Couple of questions regarding Custom Goals

### ISSUE THREAD

**Issue by Cerberus-Malthael** [lyrgard/ffbeEquip#226]
Hello,

My first question is - what is the variable for innate/passive physical draw?  I vaguely recall finding one somewhere on the FFBraveExvius subreddit at some point, but I can't recall it and it's not in the list of variables on the Custom Goal page of the Builder.  Additionally, could you please add this to that page?

For my second question - is there a variable for chance to not be targeted?  If so, could it also be added to the Custom Goal page?

Thank you very much, and I really appreciate the effort put into this project.  It's hugely helpful, especially when you have your units & inventory recorded.

**Comment by lyrgard** [comment]
Hello,

There is no custom goal for passive draw attack yet, simply because there are not enough source of Draw attack make it needed, I think. All the sources can be found here : https://ffbeequip.com/index.html#eyJzZWFyY2giOiJJbmNyZWFzZSBjaGFuY2Ugb2YgYmVpbmcgdGFyZ2V0ZWQifQ==

I intends to add that as a search criteria for the unit search page.

The same answer is also valid for camouflage. The list of items that produce that effect : https://ffbeequip.com/index.html#eyJzZWFyY2giOiJSZWR1Y2UgY2hhbmNlIG9mIGJlaW5nIHRhcmdldGVkIn0=
