### ISSUE TITLE
Unmatched Wizardry calculation error with Trance Terra in Builder

### ISSUE THREAD

**Issue by cguigue** [lyrgard/ffbeEquip#268]
![image](https://user-images.githubusercontent.com/11663743/46832745-d815ae00-cd74-11e8-8f73-08535128e9e3.png)
http://ffbeEquip.com/builder.html?server=GL#227e5d70-cd98-11e8-a3d0-07fd811772ef
So I entered all my Esper, equipment, and unit information, and I've confirmed twice over that it is indeed correct. I built my 7* Max pot, Max Level Trance Terra as shown in the picture above which lists 1634MAG, but in-game this is not the case, my MAG is listed at 1676. I am uncertain if this is a glitch in-game or with the buider's calculations. 339,843,059 if you wish to confirm for yourself.
I don't know if this is a problem with any other unit other than TT.

**Comment by lyrgard** [comment]
It is a known bug with Unmatched Wizardry and unit innate MAG TDH. Here TTerra has innate 30% MAG TDH and 50% MAG TDH from Unmatched Wizardry, so her equipment MAG should be multiplied by 1.8

The bug is that in game, currently, innate TDH and Unmatched Wizardry stacks multiplicatively instead of additively. So the equipment ATK is multiplied by 1.3 x 1.5 = 1.95 instead of 1.8 as it should. It is a bug in game, but as it is positive for the player, we try not to mention it too much so that gumi doesn't correct it ;-)

I should probably modify the builder to reflect that, but the exact trigger of the bug is not well known, so I keep a more conservative approach for now

**Comment by cguigue** [comment]
Thanks for the explanation :D hopefully they don't notice it along with the Infinite Quad Cast!
