### ISSUE TITLE
Adding CORS headers

### ISSUE THREAD

**Issue by lyrgard** [lyrgard/ffbeEquip#292]
I'm trying to add CORS header to my server, so that the new version I'm developing can access the backend.  Specifically, the new version is currently hosted here : https://lyrgard.github.io/ffbeEquipNG

I tried using https://www.npmjs.com/package/cors to add that feature, but while it works on my computer, the Access-Control-Allow-Origin header is not sent in production.

```
var cors = require('cors');

let corsOptions = {
  origin: 'https://lyrgard.github.io',
}
app.use(cors(corsOptions));
```

Any idea of something that could block it ? could it be Apache removing it ? @Adezandee @Indigo744

**Comment by Indigo744** [comment]
Got some time to look into it.

I have no idea, actually 🙁 

I wonder if, due to the Apache Proxy, the URL really seen by the app is really `https://lyrgard.github.io`?
You could try setting the `origin` parameter to a function (see [an example](https://www.npmjs.com/package/cors#configuring-cors-w-dynamic-origin) or [the doc](https://www.npmjs.com/package/cors#configuration-options)) and use a debug print to check it server side.

**Comment by lyrgard** [comment]
I'm now sorry I pinged you guys, it strangely begin to work by itself... probably a browser cache or something, I don't understand.

Well, it is olved anyway.
