### ISSUE TITLE
Monster resistances slow down builds

### ISSUE THREAD

**Issue by mkujawa** [lyrgard/ffbeEquip#369]
When the builder is considering which items to include, it will include weapons that have elements the enemy is weak against since it might be worth giving up some (for example) ATK in order to get that bonus damage.

However, this check is just inequality to 0, not _less than_ 0.  As a result, if you set the enemy ice resist to, say, 9999, the builder will now include ice weapons in the build, slowing it down.

**Comment by tomurderthelight** [comment]
copy/paste from cord before it gets lost. 

>Canine
> so i'm thinking `addDesirableElementsFromFormula(formula)` in dataStorage.js would need to be modified to check for positive resistance values and not add those to the desired element list, or something would have to be added to remove them after the fact, but i'm out of my depth and out of time right now...maybe Beedazzle has some thoughts, if not I'll play with it more in the morning
>
>builder.js will probably have to be modified where it initially looks at "ennemy" resists, might be easiest to create a new different list of desirable elements, since the existing list is used in a few places, and use that new list only when setting up the desirable elements

**Comment by tomurderthelight** [comment]
> However, this check is just inequality to 0, not _less than_ 0. As a result, if you set the enemy ice resist to, say, 9999, the builder will now include ice weapons in the build, slowing it down.

rereading some. @mkujawa do you remember where that bit of code was?

**Comment by Darwe-Canine** [comment]
For an example, using my equipment (because I forgot to set it to all equipment before starting) and building A.I. Katy for physical damage vs a enemy of no type, with 100 dark resist, the builder tried 14,485,176 builds, and dataStorage.dataByType kept the following katana:
0: {item: {…}, name: "Suiryuken", defenseValue: 1100, mpValue: 0, available: 1, …}
1: {item: {…}, name: "Suiryuken", defenseValue: 0, mpValue: 0, available: 1, …}
2: {item: {…}, name: "Onimaru+", defenseValue: 30, mpValue: 0, available: 1, …}
3: {item: {…}, name: "Water Dragon - Replica", defenseValue: 0, mpValue: 0, available: 1, …}
4: {item: {…}, name: "Muramasa (FFBE)", defenseValue: 0, mpValue: 0, available: 1, …}
5: {item: {…}, name: "Masamune (FFX)", defenseValue: 0, mpValue: 105, available: 1, …}
6: {item: {…}, name: "Kotetsu (FFIII)", defenseValue: 0, mpValue: 0, available: 1, …}
7: {item: {…}, name: "Murakumo (FFIII)", defenseValue: 550, mpValue: 0, available: 1, …}
8: {item: {…}, name: "Light Blade", defenseValue: 0, mpValue: 0, available: 1, …}
9: {item: {…}, name: "Masamune (FFVII)", defenseValue: 1100, mpValue: 0, available: 1, …}
10: {item: {…}, name: "Hyomonto", defenseValue: 825, mpValue: 0, available: 1, …}
11: {item: {…}, name: "Raikiri", defenseValue: 0, mpValue: 0, available: 1, …}
length: 12

Kotetsu (FFIII) has no IW enhancements, 105 atk, and dark element. It is completely inferior to Masamune (FFX) (184 atk elementless 30% MP, no IW), Masamune (FFVII) (150 atk elementless, doublehand, plus IW), Muramasa (FFBE) (172 atk elementless, killers, plus IW), Murakumo (FFIII) (168 atk dark element, plus IW) and possibly other katana as well. This only makes sense if the builder is keeping at least two dark katana, in addition to all of the other katana that are kept on their own merits. Other dark weapons are kept as well, just looking at one clear example.

Attempting the exact same build with all resists set to 0, the builder tries 11,022,591 builds, and keeps all of the katana above EXCEPT Kotetsu. There is no reason that having a final resistance greater than zero should add weight to weapons of that element. If final resist for an element is greater than 0, and there are no other factors (passives, materia, etc) causing an element to be added to DesirableElements list, no build will be improved by including weapons of that element just because of the element.

**Comment by Darwe-Canine** [comment]
Fix pushed 19 Nov, can be closed.

**Comment by mkujawa** [comment]
Confirmed
