### ISSUE TITLE
mag eHp and general mitigation bug

### ISSUE THREAD

**Issue by cloudix1** [lyrgard/ffbeEquip#412]
Hi 

If you try to make a build with say hp * spr > 25200000 (aigion trial stuff lol) and you have general mitigation set to 50%..

The builds you get will have a mag ehp  of double that amount. (as if there was no mitigation at all)

Below is a build I'm doing with 50% global mitigation. (i'm calculating for 12600000 as that's how I get the correct mag eHP of 25200000)
![image](https://user-images.githubusercontent.com/42959911/68842410-3e7aa780-06be-11ea-9445-fb50bb47b6d2.png)

**Comment by lyrgard** [comment]
That's not wrong. I mean, the displayed in the builder m eHP is not just HP * SPR, but also takes mitigation into account.

**Comment by cloudix1** [comment]
yes but if you see that I'm aiming for (in that image) 12600000 eHP buit the build tries to hit 25200000 eHP

**Comment by Darwe-Canine** [comment]
The MeHP value displayed isn't actually HP*SPR, it is HP*SPR*Mitigtion; the build displayed shows 17717 HP and 743 SPR, which is 13,163,731 (slightly over the 12.6m value you are aiming for). So the builder is building for the goal you asked it for, but you asked it for HP*SPR specifically, not HP*SPR*Mitigation. Since you can't currently enter mitigation as a goal like that, you just have to manually lower your goal to account for the mitigation you have.

**Comment by lyrgard** [comment]
I think @Darwe-Canine said it all. Do you have something to add, @cloudix1 ? Else I'll close the issue.
